language: python
python:
- 2.6
- 2.7
- 3.4
- 3.5
- 3.6
- pypy
- pypy3
addons:
  apt:
    packages:
    - libmms0
before_script:
- wget https://mediaarea.net/download/binary/libzen0/0.4.37/libzen0_0.4.37-1_amd64.xUbuntu_14.04.deb
- wget https://mediaarea.net/download/binary/libmediainfo0/17.10/libmediainfo0_17.10-1_amd64.xUbuntu_14.04.deb
- ar x libzen0_0.4.37-1_amd64.xUbuntu_14.04.deb
- tar xf data.tar.xz
- ar x libmediainfo0_17.10-1_amd64.xUbuntu_14.04.deb
- tar xf data.tar.xz
- pip install pytest-runner
script: LD_LIBRARY_PATH=usr/lib/x86_64-linux-gnu/ python setup.py test
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  skip_upload_docs: true
  provider: pypi
  user: sbraz
  password:
    secure: PPuAhhXw9Ccs0ydbCSaEwocIzIDN6YrT0pWA9HHIBD2NVSFcgr0TBS/D0g2xUOCJtrXt4VlMYmgNop8vA/JjgiRWze6t1SPAKawbHqmVtCUORqqxWOWxXSh330LgWZyXnpsGpAyWSozG7cwJ3AGNsGfmxs8las4qgSWG5o9v/mA=
  on:
    tags: true
