os: linux
language: python
python:
- 2.6
- 2.7
- 3.4
- 3.5
- 3.6
- pypy
- pypy3
addons:
  apt:
    packages:
    - libmms0
matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON_VERSION=2.7
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.4
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.5
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.6
before_install: |
  if [ $TRAVIS_OS_NAME == osx ]; then
    git clone https://github.com/MacPython/terryfy
    rm terryfy/test_travisparse.py
    source terryfy/travis_tools.sh
    get_python_environment macpython $PYTHON_VERSION venv
    wget https://mediaarea.net/download/binary/libmediainfo0/17.12/MediaInfo_DLL_17.12_Mac_i386+x86_64.tar.bz2
    tar xf MediaInfo_DLL_17.12_Mac_i386+x86_64.tar.bz2
  else
    wget https://mediaarea.net/download/binary/libzen0/0.4.37/libzen0_0.4.37-1_amd64.xUbuntu_14.04.deb
    wget https://mediaarea.net/download/binary/libmediainfo0/17.10/libmediainfo0_17.10-1_amd64.xUbuntu_14.04.deb
    ar x libzen0_0.4.37-1_amd64.xUbuntu_14.04.deb
    tar xf data.tar.xz
    ar x libmediainfo0_17.10-1_amd64.xUbuntu_14.04.deb
    tar xf data.tar.xz
  fi
  pip install pytest pytest-runner setuptools_scm
script: |
  if [ $TRAVIS_OS_NAME == osx ]; then
    LD_LIBRARY_PATH=MediaInfoLib/ python setup.py test
  else
    LD_LIBRARY_PATH=usr/lib/x86_64-linux-gnu/ python setup.py test
  fi
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  skip_upload_docs: true
  provider: pypi
  user: sbraz
  password:
    secure: PPuAhhXw9Ccs0ydbCSaEwocIzIDN6YrT0pWA9HHIBD2NVSFcgr0TBS/D0g2xUOCJtrXt4VlMYmgNop8vA/JjgiRWze6t1SPAKawbHqmVtCUORqqxWOWxXSh330LgWZyXnpsGpAyWSozG7cwJ3AGNsGfmxs8las4qgSWG5o9v/mA=
  on:
    branch: master
    tags: true
    python: 3.6
